name: .NET Framework Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: NuGet restore
        run: nuget restore BloodBagScanner.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build solution
        run: msbuild BloodBagScanner.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: BloodBagScanner\bin\x64\Release
